#pragma once

#include "separated_ctrl_block_allocator.h"
#include "ictrl_block.h"
#include "separated_ctrl_block_common.h"
#include <memory/allocator/allocator.h>

#include <stddef.h> // offsetof

/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>>
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)\
DECLARE_STRUCT_SUBTYPE(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), value_type, TYPE);\
DECLARE_STRUCT_SUBTYPE(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), allocator_type, ALLOCATOR);\
/* here we expect that its interface was defined before*/\
typedef struct RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR) {\
    struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC) inherited_abstract_object;\
    STRUCT_SUBTYPE(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), value_type)* value;\
    STRUCT_SUBTYPE(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), allocator_type) allocator;\
    ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC) ctrl_block_allocator;\
} RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)
/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, DEFAULT_ALLOCATOR_TYPE(TYPE))
/// struct rc<Type, StrongRC=usize, WeakRC=usize>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE(TYPE)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC(TYPE, usize, usize)
/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>>::vtable variable
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC__ALLOCATOR_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)\
    DECLARE_CONTAINER_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(\
        MODIFIER,\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR),\
        RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)\
    )
/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>::vtable variable
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC)\
    DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC__ALLOCATOR_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, DEFAULT_ALLOCATOR_TYPE(TYPE))
/// struct rc<Type, StrongRC=usize, WeakRC=usize>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>::vtable variable
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE)\
    DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC_WITH_MODIFIER(MODIFIER, TYPE, usize, usize)
///
/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>> methods
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)\
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR));\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, dispose_value)(\
        struct RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this);\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, dispose_this)(\
        struct RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this);\
MODIFIER void*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(destroy_at))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const this);\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_this))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const this);\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_value))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const this)

/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>> methods
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC)\
    DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, DEFAULT_ALLOCATOR_TYPE(TYPE))
/// struct rc<Type, StrongRC=usize, WeakRC=usize>::DefaultSeparatedCtrlBlock methods
#define DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
    DECLARE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC_METHODS_WITH_MODIFIER(MODIFIER, TYPE, usize, usize)

/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>>::vtable variable init
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC__ALLOCATOR_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)\
    DECLARE_CONTAINER_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(\
        MODIFIER,\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR),\
        RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)\
    ) = {\
        .dispose_value = RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_value)),\
        .dispose_this = RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_this)),\
        .destroy_at = RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(destroy_at))\
    }
/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>::vtable variable init
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC__ALLOCATOR_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, DEFAULT_ALLOCATOR_TYPE(TYPE))
/// struct rc<Type, StrongRC=usize, WeakRC=usize>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>>::vtable variable init
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_INTERFACE_VTABLE_VARIABLE__STRONG_RC__WEAK_RC_WITH_MODIFIER(MODIFIER, TYPE, usize, usize)

/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>> methods definition
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)\
MODIFIER RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, construct_at)(\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this) {\
    ASSERT(this);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, construct_at)(&this->inherited_abstract_object);\
    this->inherited_abstract_object.INTERFACE_VTABLE_VARIABLE(RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)) =\
        &CONTAINER_INTERFACE_VTABLE_STATIC_VARIABLE(\
            RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR),\
            RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)\
        );\
    this->value = NULL;\
    TYPE_METHOD(ALLOCATOR, construct_at)(&this->allocator);\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), construct_at)(&this->ctrl_block_allocator);\
    return this;\
}\
MODIFIER RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, construct_copy_at)(\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this,\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR) const* const src) {\
    ASSERT(this);\
    ASSERT(src);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, construct_copy_at)(\
        &this->inherited_abstract_object,\
        &src->inherited_abstract_object\
    );\
    this->inherited_abstract_object.INTERFACE_VTABLE_VARIABLE(RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)) =\
        &CONTAINER_INTERFACE_VTABLE_STATIC_VARIABLE(\
            RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR),\
            RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)\
        );\
    this->value = src->value;\
    TYPE_METHOD(ALLOCATOR, construct_copy_at)(&this->allocator, &src->allocator);\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), construct_copy_at)(\
        &this->ctrl_block_allocator,\
        &src->ctrl_block_allocator\
    );\
    return this;\
}\
MODIFIER RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, construct_move_at)(\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this,\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const src) {\
    ASSERT(this);\
    ASSERT(src);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, construct_move_at)(\
        &this->inherited_abstract_object,\
        &src->inherited_abstract_object\
    );\
    this->inherited_abstract_object.INTERFACE_VTABLE_VARIABLE(RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)) =\
        &CONTAINER_INTERFACE_VTABLE_STATIC_VARIABLE(\
            RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR),\
            RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)\
        );\
    this->value = src->value; src->value = NULL;\
    TYPE_METHOD(ALLOCATOR, construct_move_at)(&this->allocator, &src->allocator);\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), construct_move_at)(\
        &this->ctrl_block_allocator,\
        &src->ctrl_block_allocator\
    );\
    return this;\
}\
DEFINE_DEFAULT_ASSIGNMENT_METHODS_WITH_MODIFIER(MODIFIER, RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR))\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, swap)(\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this,\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const src) {\
    ASSERT(this);\
    ASSERT(src);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, swap)(\
        &this->inherited_abstract_object,\
        &src->inherited_abstract_object\
    );\
    TYPE_METHOD(voidptr, swap)((voidptr*)&this->value, (voidptr*)&src->value);\
    TYPE_METHOD(ALLOCATOR, swap)(&this->allocator, &src->allocator);\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), swap)(\
        &this->ctrl_block_allocator,\
        &src->ctrl_block_allocator\
    );\
}\
MODIFIER void*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, destroy_at)(\
        RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this) {\
    ASSERT(this);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, destroy_at)(&this->inherited_abstract_object);\
    return this;\
}\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, dispose_value)(\
        struct RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this) {\
    ASSERT(this);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, dispose_value)(&this->inherited_abstract_object);\
}\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, dispose_this)(\
        struct RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this) {\
    ASSERT(this);\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, dispose_this)(&this->inherited_abstract_object);\
}\
MODIFIER void*\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(destroy_at))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const base) {\
    /* boilerplate (base to derived) */\
    ASSERT(base);\
    void* const void_this = (char*)base -\
        offsetof(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), inherited_abstract_object);\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this =\
        (RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*)void_this;\
    /* call this::destroy_at instructions */\
    TYPE_METHOD(ALLOCATOR, destroy_at)(&this->allocator);\
    /* call interface::destroy_at */\
    RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC_METHOD(STRONG_RC, WEAK_RC, VTABLE_MEMBER(destroy_at))(base);\
    return this;\
}\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_this))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const base) {\
    /* boilerplate (base to derived) */\
    ASSERT(base);\
    void* const void_this = (char*)base -\
        offsetof(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), inherited_abstract_object);\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this =\
        (RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*)void_this;\
    /* move this::ctrl_block_allocator to temporary allocator's storage (temp_ctrl_block_allocator) & destroy this::ctrl_block_allocator before deallocation */\
    ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC) temp_ctrl_block_allocator;\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), construct_move_at)(\
        &temp_ctrl_block_allocator,\
        &this->ctrl_block_allocator\
    );\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), destroy_at)(&this->ctrl_block_allocator);\
    /* deallocate memory from this by temporary allocator object (temp_ctrl_block_allocator) */\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), deallocate)(\
        &temp_ctrl_block_allocator,\
        this,\
        1u);\
    /* destroy temporary allocator's storage (temp_ctrl_block_allocator) */\
    TYPE_METHOD(ALLOCATOR_TYPE__RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC(TYPE, STRONG_RC, WEAK_RC), destroy_at)(&temp_ctrl_block_allocator);\
}\
MODIFIER void\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHOD(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR, VTABLE_MEMBER(dispose_value))(\
        struct RC_CTRL_BLOCK_INTERFACE_TYPE__STRONG_RC__WEAK_RC(STRONG_RC, WEAK_RC)* const base) {\
    /* boilerplate (base to derived) */\
    ASSERT(base);\
    void* const void_this = (char*)base -\
        offsetof(RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR), inherited_abstract_object);\
    RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)* const this =\
        (RC_DEFAULT_SEPARATED_CTRL_BLOCK_TYPE__STRONG_RC__WEAK_RC__ALLOCATOR(TYPE, STRONG_RC, WEAK_RC, ALLOCATOR)*)void_this;\
    /* call this::dispose_value instructions */\
    if (this->value) {\
        TYPE_METHOD(TYPE, destroy_at)(this->value);\
        TYPE_METHOD(ALLOCATOR, deallocate)(&this->allocator, this->value, 1u);\
        this->value = NULL;\
    }\
}\

/// struct rc<Type, StrongRC, WeakRC>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>> methods definition
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC__ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, STRONG_RC, WEAK_RC, DEFAULT_ALLOCATOR_TYPE(TYPE))
/// struct rc<Type, StrongRC=usize, WeakRC=usize>::DefaultSeparatedCtrlBlock<Allocator<Type>=DefaultAllocator<Type>> methods definition
#define DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
    DEFINE_RC_DEFAULT_SEPARATED_CTRL_BLOCK__STRONG_RC__WEAK_RC_METHODS_WITH_MODIFIER(MODIFIER, TYPE, usize, usize)
