#pragma once

#include "set_methods_decl.h"

// set non-dynamic 'dynamic' inner methods
#define DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(COMMON_MODIFIER, TYPE)\
/* --- Set interface methods --- */\
/* --- Construction/Destruction functions --- */\
COMMON_MODIFIER void* SET_INTERFACE_METHOD(TYPE, VTABLE_MEMBER(destroy_at))(\
    struct SET_INTERFACE_TYPE(TYPE)* const this);\
/* --- Mutable iterator's methods --- */\
/* --- Construction/Destruction functions --- */\
COMMON_MODIFIER void* SET_INTERFACE_ITERATOR_METHOD(TYPE, VTABLE_MEMBER(destroy_at))(\
    struct SET_INTERFACE_ITERATOR_TYPE(TYPE)* const this);\
/* --- Const iterator's methods --- */\
/* --- Construction/Destruction functions --- */\
COMMON_MODIFIER void* SET_INTERFACE_CONST_ITERATOR_METHOD(TYPE, VTABLE_MEMBER(destroy_at))(\
    struct SET_INTERFACE_CONST_ITERATOR_TYPE(TYPE)* const this);\

#define DECLARE_SET_INTERFACE_INHERITANCE_METHODS(TYPE) DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(, TYPE)
#define DECLARE_SET_INTERFACE_STATIC_INHERITANCE_METHODS(TYPE) DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(static, TYPE)
#define DECLARE_SET_INTERFACE_INLINE_INHERITANCE_METHODS(TYPE) DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(inline, TYPE)
#define DECLARE_SET_INTERFACE_EXTERNAL_INHERITANCE_METHODS(TYPE) DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(extern, TYPE)
#define DECLARE_SET_INTERFACE_EXTERNAL_INLINE_INHERITANCE_METHODS(TYPE) DECLARE_SET_INTERFACE_INHERITANCE_METHODS_WITH_MODIFIER(extern inline, TYPE)
