#include "characters_helpers.h"

DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char8)
DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char16)
DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char32)
DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char64)

DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, wchar)

#if defined(_WIN32)
    DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, winchar)
#endif
