#pragma once

#include "numeric_helpers.h"

#include <primitives/characters_types_aliases.h>

DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char8);
DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char16);
DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char32);
DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char64);

DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, wchar);

#if defined(_WIN32)
    DECLARE_NUMERIC_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, winchar);
#endif
