#pragma once

#include "numeric_helpers.h"
#include <primitives/data_model_types_aliases.h>

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, usize);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, ptrdiff);

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, intptr);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uintptr);

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, voidptr);
