#pragma once

#include <primitives/unsigned_types_aliases.h>
#include <primitives/fixed_size_types_aliases.h>
#include <utils/macros.h>

#ifndef FLOAT_INTEGER_PUNNING_TYPE
	#define FLOAT_INTEGER_PUNNING_TYPE uint32
#endif

#ifndef DOUBLE_INTEGER_PUNNING_TYPE
	#define DOUBLE_INTEGER_PUNNING_TYPE uint64
#endif

#define DEFINE_NUMERIC_TYPE_COMMON_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
MODIFIER TYPE* TYPE_METHOD(TYPE, construct_at)(TYPE* const this) {\
	ASSERT(this);\
	*this = 0;\
	return this;\
}\
MODIFIER TYPE* TYPE_METHOD(TYPE, construct_copy_at)(TYPE* const this, TYPE const* const src) {\
	ASSERT(this);\
	ASSERT(src);\
	*this = *src;\
	return this; \
}\
MODIFIER TYPE* TYPE_METHOD(TYPE, construct_move_at)(TYPE* const this, TYPE* const src) {\
	return TYPE_METHOD(TYPE, construct_copy_at)(this, src);\
}\
MODIFIER void* TYPE_METHOD(TYPE, destroy_at)(TYPE* const this) {\
	return this;\
}\
MODIFIER TYPE* TYPE_METHOD(TYPE, assign_copy_at)(TYPE* const this, TYPE const* const src) {\
	return TYPE_METHOD(TYPE, construct_copy_at)(this, src);\
}\
MODIFIER TYPE* TYPE_METHOD(TYPE, assign_move_at)(TYPE* const this, TYPE* const src) {\
	return TYPE_METHOD(TYPE, construct_move_at)(this, src);\
}


#define DEFINE_INTEGER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
DEFINE_NUMERIC_TYPE_COMMON_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
MODIFIER void TYPE_METHOD(TYPE, swap)(TYPE* const this, TYPE* const src) {\
	ASSERT(this);\
	ASSERT(src);\
	*this ^= *src;\
	*src ^= *this;\
	*this ^= *src;\
}

#define DEFINE_FLOAT_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
DEFINE_NUMERIC_TYPE_COMMON_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
MODIFIER void TYPE_METHOD(TYPE, swap)(TYPE* const this, TYPE* const src) {\
	ASSERT(this);\
	ASSERT(src);\
	STATIC_ASSERT(SIZEOF(TYPE) == SIZEOF(FLOAT_INTEGER_PUNNING_TYPE));\
	TYPE_METHOD(FLOAT_INTEGER_PUNNING_TYPE, swap)((FLOAT_INTEGER_PUNNING_TYPE*)this, (FLOAT_INTEGER_PUNNING_TYPE*)(src));\
}

#define DEFINE_DOUBLE_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
DEFINE_NUMERIC_TYPE_COMMON_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
MODIFIER void TYPE_METHOD(TYPE, swap)(TYPE* const this, TYPE* const src) {\
	ASSERT(this);\
	ASSERT(src);\
	STATIC_ASSERT(SIZEOF(TYPE) == SIZEOF(DOUBLE_INTEGER_PUNNING_TYPE));\
	TYPE_METHOD(DOUBLE_INTEGER_PUNNING_TYPE, swap)((DOUBLE_INTEGER_PUNNING_TYPE*)this, (DOUBLE_INTEGER_PUNNING_TYPE*)(src));\
}

#define DEFINE_POINTER_TYPE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
DEFINE_NUMERIC_TYPE_COMMON_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
MODIFIER void TYPE_METHOD(TYPE, swap)(TYPE* const this, TYPE* const src) {\
	ASSERT(this);\
	ASSERT(src);\
	STATIC_ASSERT(SIZEOF(TYPE) == SIZEOF(uintptr));\
	TYPE_METHOD(uintptr, swap)((uintptr*)this, (uintptr*)(src));\
}

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, char);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, short);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, int);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, long);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uchar);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, ushort);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uint);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, ulong);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, float);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, double);

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, int8);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, int16);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, int32);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, int64);

DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uint8);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uint16);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uint32);
DECLARE_DEFAULT_LIFECYCLE_METHODS_WITH_MODIFIER(, uint64);
