#include "compare.h"

DEFINE_RAW_STRING_COMPARE_FUNCTION(char)
DEFINE_RAW_STRING_COMPARE_FUNCTION(char8)
DEFINE_RAW_STRING_COMPARE_FUNCTION(char16)
DEFINE_RAW_STRING_COMPARE_FUNCTION(char32)
DEFINE_RAW_STRING_COMPARE_FUNCTION(char64)

DEFINE_RAW_STRING_COMPARE_FUNCTION(wchar)

#if defined(_WIN32)
    DEFINE_RAW_STRING_COMPARE_FUNCTION(winchar)
#endif
