#include "c_string_helpers.h"

DEFINE_C_STRING_LENGTH_FUNCTION(char);
DEFINE_C_STRING_LENGTH_FUNCTION(char8);
DEFINE_C_STRING_LENGTH_FUNCTION(char16);
DEFINE_C_STRING_LENGTH_FUNCTION(char32);
DEFINE_C_STRING_LENGTH_FUNCTION(char64);
