
#pragma once

#include <utils/string/raw_string/compare.h>
#include <utils/array/compare.h>

#include <containers/dynamic/string/string.h>
#include <containers/static/string_view/string_view.h>
#include <utils/string/common.h>
#include <primitives/unsigned_types_aliases.h>
#include <primitives/characters_types_aliases.h>

#define DECLARE_STRING_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_TYPE)\
MODIFIER int STRING_FUNCTION(STRING_TYPE, compare)(STRING_TYPE const* const string1, STRING_TYPE const* const string2)

#define DECLARE_STRING_COMPARE_FUNCTION(STRING_TYPE)\
    DECLARE_STRING_COMPARE_FUNCTION_WITH_MODIFIER(, STRING_TYPE)

#define DEFINE_STRING_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_TYPE)\
MODIFIER int STRING_FUNCTION(STRING_TYPE, compare)(STRING_TYPE const* const string1, STRING_TYPE const* const string2) {\
    ASSERT(string1);\
    ASSERT(string2);\
    return RAW_STRING_FUNCTION(STRUCT_SUBTYPE(STRING_TYPE, char_type), compare)(TYPE_METHOD(STRING_TYPE, data)(string1), TYPE_METHOD(STRING_TYPE, data)(string2));\
}

#define DEFINE_STRING_COMPARE_FUNCTION(CHAR_TYPE)\
    DEFINE_STRING_COMPARE_FUNCTION_WITH_MODIFIER(, CHAR_TYPE)

#define DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(MODIFIER, STRING_TYPE)\
DECLARE_RAW_STRING_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRUCT_SUBTYPE(STRING_TYPE, char_type));\
DECLARE_STRING_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_TYPE)

DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(char));
DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(char8));
DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(char16));
DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(char32));
DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(char64));

DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(wchar));

#if defined(_WIN32)
    DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_TYPE(winchar));
#endif

#undef DECLARE_STRING_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER

#define DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_VIEW_TYPE)\
    MODIFIER int STRING_FUNCTION(STRING_VIEW_TYPE, compare)(STRING_VIEW_TYPE const* const string_view1, STRING_VIEW_TYPE const* const string_view2)

#define DECLARE_STRING_VIEW_COMPARE_FUNCTION(STRING_VIEW_TYPE)\
    DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_MODIFIER(, STRING_VIEW_TYPE)

#define DEFINE_STRING_VIEW_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_VIEW_TYPE)\
MODIFIER int STRING_FUNCTION(STRING_VIEW_TYPE, compare)(STRING_VIEW_TYPE const* const string1, STRING_VIEW_TYPE const* const string2) {\
    ASSERT(string1);\
    ASSERT(string2);\
    return RAW_ARRAY_FUNCTION(STRUCT_SUBTYPE(STRING_VIEW_TYPE, char_type), compare)(\
        TYPE_METHOD(STRING_VIEW_TYPE, data)(string1), TYPE_METHOD(STRING_VIEW_TYPE, size)(string1),\
        TYPE_METHOD(STRING_VIEW_TYPE, data)(string2), TYPE_METHOD(STRING_VIEW_TYPE, size)(string2)\
    );\
}

#define DEFINE_STRING_VIEW_COMPARE_FUNCTION(CHAR_TYPE)\
    DEFINE_STRING_VIEW_COMPARE_FUNCTION_WITH_MODIFIER(, CHAR_TYPE)

#define DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(MODIFIER, STRING_VIEW_TYPE)\
DECLARE_RAW_ARRAY_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRUCT_SUBTYPE(STRING_VIEW_TYPE, char_type));\
DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_MODIFIER(MODIFIER, STRING_VIEW_TYPE)

DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(char));
DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(char8));
DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(char16));
DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(char32));
DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(char64));

DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(wchar));

#if defined(_WIN32)
    DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER(extern, SPECIALIZED_STRING_VIEW_TYPE(winchar));
#endif

#undef DECLARE_STRING_VIEW_COMPARE_FUNCTION_WITH_HELPER_RAW_STRING_COMPARE_FUNCTION_AND_MODIFIER
