#include "convert.h"

DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,char, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,uchar, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,short, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,ushort, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,int, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,uint, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,long, STRING_TYPE())
DEFINE_CONVERT_NUMERIC_TYPE_TO_STRING_TYPE_WITH_MODIFIER(,ulong, STRING_TYPE())
