#pragma once

#include "helpers.h"

DECLARE_NUMERIC_TYPE_TO_STRING(char);
DECLARE_NUMERIC_TYPE_TO_STRING(uchar);
DECLARE_NUMERIC_TYPE_TO_STRING(short);
DECLARE_NUMERIC_TYPE_TO_STRING(ushort);
DECLARE_NUMERIC_TYPE_TO_STRING(int);
DECLARE_NUMERIC_TYPE_TO_STRING(uint);
DECLARE_NUMERIC_TYPE_TO_STRING(long);
DECLARE_NUMERIC_TYPE_TO_STRING(ulong);
