#include "numeric_type_to_string_impl.h"
#include <containers/string_impl.h>

IMPLEMENT_NUMERIC_TYPE_TO_STRING(char);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(uchar);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(short);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(ushort);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(int);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(uint);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(long);
IMPLEMENT_NUMERIC_TYPE_TO_STRING(ulong);
