#pragma once

#include <containers/common.h>

// iterators' macro heplers definitions
#define ITERATOR_TYPE(CONTAINER_TYPE) TYPE_MEMBER(CONTAINER_TYPE, iterator)
#define ITERATOR_METHOD(CONTAINER_TYPE, METHOD) TYPE_METHOD(ITERATOR_TYPE(CONTAINER_TYPE), METHOD)

#define CONST_ITERATOR_TYPE(CONTAINER_TYPE) TYPE_MEMBER(ITERATOR_TYPE(CONTAINER_TYPE), const)
#define CONST_ITERATOR_METHOD(CONTAINER_TYPE, METHOD) TYPE_METHOD(CONST_ITERATOR_TYPE(CONTAINER_TYPE), METHOD)

#define REVERSE_ITERATOR_TYPE(ITERATOR_TYPE) TYPE_MEMBER(ITERATOR_TYPE, reversed)
#define REVERSE_ITERATOR_METHOD(ITERATOR_TYPE, METHOD) TYPE_METHOD(REVERSE_ITERATOR_TYPE(ITERATOR_TYPE), METHOD)
