#pragma once

#include "rb_tree_set_inheritance_methods_decl.h"
#include "rb_tree_set_types_decl.h"

#define DEFINE_RED_BLACK_TREE_SET_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR)\
    DECLARE_CONTAINER_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER,\
        RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR(TYPE, COMPARATOR, ALLOCATOR),\
        SET_INTERFACE_TYPE(TYPE)) = {\
    .destroy_at = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(destroy_at)),\
    .clear = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(clear)),\
    .size = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(size)),\
    /* insert element */\
    .insert_copy = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(insert_copy)),\
    .insert_move = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(insert_move)),\
    /* find element */\
    .find = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(find)),\
    .mut_find = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(mut_find)),\
    /* erase element */\
    .erase_by_iterator = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(erase_by_iterator)),\
    .erase_by_const_iterator = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(erase_by_const_iterator)),\
    /* basic iterators' construction methods */\
    .begin = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(begin)),\
    .end = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(end)),\
    .cbegin = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(cbegin)),\
    .cend = &RED_BLACK_TREE_SET_TYPE_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(cend))\
}

#define DEFINE_RED_BLACK_TREE_SET_INTERFACE_ITERATOR_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR)\
    DECLARE_CONTAINER_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER,\
        RED_BLACK_TREE_SET_ITERATOR_TYPE_WITH_COMPARATOR_AND_ALLOCATOR(TYPE, COMPARATOR, ALLOCATOR),\
        SET_INTERFACE_ITERATOR_TYPE(TYPE)) = {\
    .destroy_at = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(destroy_at)),\
    /* --- Element access functions --- */\
    .value = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(value)),\
    .const_value = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(const_value)),\
    /* --- Compare functions --- */\
    /* return 0 if equals, !0 either */\
    .compare = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(compare)),\
    /* --- Increment functions --- */\
    /* point this to next value & return this-value */\
    .next = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(next)),\
    /* return this-value & point this to next value */\
    .pnext = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(pnext)),\
    /* --- Decrement functions --- */\
    /* point this to previous value & return this-value */\
    .prev = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(prev)),\
    /* return this-value & point this to previous value */\
    .pprev = &RED_BLACK_TREE_SET_TYPE_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(pprev))\
}


#define DEFINE_RED_BLACK_TREE_SET_CONST_INTERFACE_ITERATOR_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR)\
    DECLARE_CONTAINER_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER,\
        RED_BLACK_TREE_SET_CONST_ITERATOR_TYPE_WITH_COMPARATOR_AND_ALLOCATOR(TYPE, COMPARATOR, ALLOCATOR),\
        SET_INTERFACE_CONST_ITERATOR_TYPE(TYPE)) = {\
    .destroy_at = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(destroy_at)),\
    /* --- Element access functions --- */\
    .value = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(value)),\
    .const_value = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(const_value)),\
    /* --- Compare functions --- */\
    /* return 0 if equals, !0 either */\
    .compare = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(compare)),\
    /* --- Increment functions --- */\
    /* point this to next value & return this-value */\
    .next = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(next)),\
    /* return this-value & point this to next value */\
    .pnext = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(pnext)),\
    /* --- Decrement functions --- */\
    /* point this to previous value & return this-value */\
    .prev = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(prev)),\
    /* return this-value & point this to previous value */\
    .pprev = &RED_BLACK_TREE_SET_TYPE_CONST_ITERATOR_WITH_COMPARATOR_AND_ALLOCATOR_METHOD(TYPE, COMPARATOR, ALLOCATOR, VTABLE_MEMBER(pprev))\
}

#define DEFINE_RED_BLACK_TREE_SET_INTERFACE_VTABLES_VARIABLES_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR)\
    DEFINE_RED_BLACK_TREE_SET_INTERFACE_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR);\
    DEFINE_RED_BLACK_TREE_SET_INTERFACE_ITERATOR_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR);\
    DEFINE_RED_BLACK_TREE_SET_CONST_INTERFACE_ITERATOR_VTABLE_VARIABLE_WITH_MODIFIER(MODIFIER, TYPE, COMPARATOR, ALLOCATOR)
