#include "string_view.h"

DEFINE_STRING_VIEW()
DEFINE_WSTRING_VIEW()
DEFINE_SPECIALIZED_STRING_VIEW(char8)
DEFINE_SPECIALIZED_STRING_VIEW(char16)
DEFINE_SPECIALIZED_STRING_VIEW(char32)
DEFINE_SPECIALIZED_STRING_VIEW(char64)

#if defined(_WIN32)
    DEFINE_SPECIALIZED_STRING_VIEW(winchar)
#endif
