#pragma once

#include <utils/string/raw_string/helpers.h>
#include <containers/dynamic/common.h>
#include <primitives/limits.h>
#include <primitives/allocator.h>

// define OS_STRING_LITERAL
#if defined(_WIN32)
    #define OS_STRING_LITERAL(STR) _TEXT(STR)
#else
    #define OS_STRING_LITERAL(STR) STR
#endif

// define macros for `string_type`
#define SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)\
    NAMESPACE_CONTAINERS_DYNAMIC(CONCAT7(string, __, TYPE, _, with_allocator, _, ALLOCATOR))
#define SPECIALIZED_STRING_TYPE(TYPE)\
    SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, DEFAULT_ALLOCATOR_TYPE(TYPE))
#define STRING_TYPE() SPECIALIZED_STRING_TYPE(char)
#define WSTRING_TYPE() SPECIALIZED_STRING_TYPE(wchar)
#define OS_STRING_TYPE() SPECIALIZED_STRING_TYPE(OS_CHAR_TYPE)

// define macros for string methods
#define SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, METHOD)\
    TYPE_METHOD(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), METHOD)
#define SPECIALIZED_STRING_METHOD(TYPE, METHOD)\
    TYPE_METHOD(SPECIALIZED_STRING_TYPE(TYPE), METHOD)
#define STRING_METHOD(METHOD) SPECIALIZED_STRING_METHOD(char, METHOD)
#define WSTRING_METHOD(METHOD) SPECIALIZED_STRING_METHOD(wchar, METHOD)
#define OS_STRING_METHOD(METHOD) TYPE_METHOD(OS_STRING_TYPE(), METHOD)

// define macro for string type
#define DECLARE_SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)\
DECLARE_STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type, usize);\
DECLARE_STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), char_type, TYPE);\
DECLARE_STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), allocator_type, ALLOCATOR);\
typedef struct STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data) {\
    TYPE* buffer;\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) size;\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) capacity;\
} STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data);\
typedef struct STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), stack_allocated_data) {\
    TYPE buffer[sizeof(struct STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data)) / sizeof(TYPE)];\
} STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), stack_allocated_data);\
typedef struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) {\
    union {\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data) dynamic_data;\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), stack_allocated_data) stack_data;\
    };\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), allocator_type) allocator;\
    uchar is_stack_allocated;\
} SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)

#define DECLARE_SPECIALIZED_STRING_TYPE(TYPE)\
DECLARE_SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, DEFAULT_ALLOCATOR_TYPE(TYPE))

// define macro for string type & string methods declaration
#define DECLARE_SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, ALLOCATOR)\
/* --- Construction/Destruction functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_copy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const source);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_move_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_by_value_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const size, TYPE const* const value);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_buffer_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size, TYPE const* const source_buffer);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_c_string_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer);\
MODIFIER void* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this);\
/* --- Assignment functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_move_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_copy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const source);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_from_buffer_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size, TYPE const* const source_buffer);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_from_c_string_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer);\
/* --- Swap --- */\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source);\
/* --- Memory managment functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, resize)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const new_size, TYPE const* const value);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const new_capacity);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, clear)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, shrink_to_fit)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this);\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const value);\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, pop_back)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_string)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* another_string);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_c_string)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const * const);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_buffer)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size);\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_fill)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const size, TYPE const* const value);\
/* --- Getters functions implementation --- */\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this);\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this);\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, length)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this);\
MODIFIER uchar SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, empty)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this);\
MODIFIER TYPE const* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, data)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this);\
MODIFIER TYPE const* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index);\
MODIFIER TYPE* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index)

#define DECLARE_SPECIALIZED_STRING_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
    DECLARE_SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, DEFAULT_ALLOCATOR_TYPE(TYPE))

// define macro for string type & string methods declaration
#define DECLARE_SPECIALIZED_STRING(TYPE)\
DECLARE_SPECIALIZED_STRING_TYPE(TYPE);\
DECLARE_SPECIALIZED_STRING_METHODS_WITH_MODIFIER(extern, TYPE)

#define DECLARE_STRING() DECLARE_SPECIALIZED_STRING(char)
#define DECLARE_WSTRING() DECLARE_SPECIALIZED_STRING(wchar)

#define DEFINE_SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, ALLOCATOR)\
/* --- Construction/Destruction functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this) {\
    static_assert(sizeof(struct STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data)) / sizeof(TYPE) > 1, "sizeof(" "##TYPE##" ") is higher than size of 3x pointers");\
    static_assert(sizeof(struct STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), dynamically_allocated_data)) / sizeof(TYPE) < MAX_VALUE(TYPE), "sizeof(" "##TYPE##" ") is higher than size of 3x pointers");\
    this->is_stack_allocated = 1u;\
    TYPE_METHOD(TYPE, construct_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, 0u));\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
    TYPE* const stack_allocated_data__capacity_element = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, capacity);\
    TYPE const casted_capacity = (TYPE const)(capacity);\
    TYPE_METHOD(TYPE, construct_copy_at)(stack_allocated_data__capacity_element, &casted_capacity);\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_copy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const source) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(this);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(source));\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const source_string_size = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(source);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < source_string_size; ++index) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(source, index));\
    }\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_move_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source) {\
    if (source->is_stack_allocated) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_copy_at)(this, source);\
        return this;\
    }\
    this->is_stack_allocated = 0u;\
    this->dynamic_data.buffer = source->dynamic_data.buffer;\
    this->dynamic_data.size = source->dynamic_data.size;\
    this->dynamic_data.capacity = source->dynamic_data.capacity;\
\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(source);\
    source->is_stack_allocated = 1u;\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_by_value_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const size, TYPE const* const value) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(this);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, size);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < size; ++index) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(this, value);\
    }\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_buffer_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size, TYPE const* const source_buffer) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(this);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, buffer_size);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < buffer_size; ++index) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(this, &source_buffer[index]);\
    }\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_c_string_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_at)(this);\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size = RAW_STRING_FUNCTION(TYPE, length)(source_buffer);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_buffer_at)(this, buffer_size, source_buffer);\
    return this;\
}\
MODIFIER void* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this) {\
    if (!this->is_stack_allocated) {\
        TYPE_METHOD(ALLOCATOR, deallocate)(&this->allocator, this->dynamic_data.buffer, this->dynamic_data.capacity);\
    };\
    return this;\
}\
/* --- Assignment functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_move_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source) {\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) temporary_string;\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_move_at)(&temporary_string, source);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(this, &temporary_string);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(&temporary_string);\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_copy_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const source) {\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) temporary_string;\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_copy_at)(&temporary_string, source);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(this, &temporary_string);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(&temporary_string);\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_from_buffer_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size, TYPE const* const source_buffer) {\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) temporary_string;\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_buffer_at)(&temporary_string, buffer_size, source_buffer);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(this, &temporary_string);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(&temporary_string);\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, assign_from_c_string_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer) {\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) temporary_string;\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_c_string_at)(&temporary_string, source_buffer);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(this, &temporary_string);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, destroy_at)(&temporary_string);\
    return this;\
}\
/* --- Swap --- */\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, swap)(\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this,\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const source) {\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const stack_allocated_capacity = sizeof(this->dynamic_data) / sizeof(TYPE);\
    if (this->is_stack_allocated && source->is_stack_allocated) {\
        for (usize index = 0u; index < stack_allocated_capacity; ++index) {\
            TYPE const temporary = this->stack_data.buffer[index];\
            this->stack_data.buffer[index] = source->stack_data.buffer[index];\
            source->stack_data.buffer[index] = temporary;\
        }\
        return;\
    }\
    if (!this->is_stack_allocated && !source->is_stack_allocated) {\
        {\
            TYPE* const temporary = this->dynamic_data.buffer;\
            this->dynamic_data.buffer = source->dynamic_data.buffer;\
            source->dynamic_data.buffer = temporary;\
        }\
        {\
            STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const temporary = this->dynamic_data.size;\
            this->dynamic_data.size = source->dynamic_data.size;\
            source->dynamic_data.size = temporary;\
        }\
        {\
            STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const temporary = this->dynamic_data.capacity;\
            this->dynamic_data.capacity = source->dynamic_data.capacity;\
            source->dynamic_data.capacity = temporary;\
        }\
        return;\
    }\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const stack_allocated_string = this->is_stack_allocated ? this : source;\
    struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const dynamically_allocated_string = source->is_stack_allocated ? this : source;\
    ASSERT(stack_allocated_string != dynamically_allocated_string);\
    {\
        TYPE temporary[sizeof(this->dynamic_data) / sizeof(TYPE)];\
        for (usize index = 0u; index < stack_allocated_capacity; ++index) {\
            temporary[index] = stack_allocated_string->stack_data.buffer[index];\
        }\
        stack_allocated_string->dynamic_data.buffer = dynamically_allocated_string->dynamic_data.buffer;\
        stack_allocated_string->dynamic_data.size = dynamically_allocated_string->dynamic_data.size;\
        stack_allocated_string->dynamic_data.capacity = dynamically_allocated_string->dynamic_data.capacity;\
        stack_allocated_string->is_stack_allocated = !(dynamically_allocated_string->is_stack_allocated = 1u);\
        for (usize index = 0u; index < stack_allocated_capacity; ++index) {\
            dynamically_allocated_string->stack_data.buffer[index] = temporary[index];\
        }\
    }\
}\
/* --- Memory managment functions implementation --- */\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, resize)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const new_size, TYPE const* const value) {\
    if (SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this) >= new_size) {\
        return this;\
    }\
    if (this->is_stack_allocated) {\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
        if (capacity >= new_size) {\
            for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this); index < new_size; ++index) {\
                TYPE_METHOD(TYPE, construct_copy_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, index), value);\
            }\
            TYPE_METHOD(TYPE, construct_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, new_size));\
            TYPE const current_extension_size = (TYPE const)(capacity - new_size);\
            TYPE* const stack_allocated_data__capacity_element = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, capacity);\
            TYPE_METHOD(TYPE, construct_copy_at)(stack_allocated_data__capacity_element, &current_extension_size);\
            return this;\
        }\
    }\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, new_size);\
    for (; this->dynamic_data.size < new_size; ++this->dynamic_data.size) {\
        TYPE_METHOD(TYPE, construct_copy_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, this->dynamic_data.size), value);\
    }\
    TYPE_METHOD(TYPE, construct_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, new_size));\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const new_capacity) {\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) current_capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
    if (current_capacity++ >= new_capacity) {\
        return this;\
    }\
    while (((current_capacity <<= 1) - 1) < new_capacity);\
    TYPE* const new_buffer = TYPE_METHOD(ALLOCATOR, allocate)(&this->allocator, current_capacity);\
    /* Copy elements one-by-one */\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this); ++index) {\
        TYPE_METHOD(TYPE, construct_copy_at)(&new_buffer[index], SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(this, index));\
    }\
    if (!this->is_stack_allocated) {\
        TYPE_METHOD(ALLOCATOR, deallocate)(&this->allocator, this->dynamic_data.buffer, this->dynamic_data.capacity);\
    }\
    this->dynamic_data.size = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this);\
    this->dynamic_data.buffer = new_buffer;\
    this->dynamic_data.capacity = current_capacity - 1;\
    this->is_stack_allocated = 0;\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, clear)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this) {\
    if (!this->is_stack_allocated) {\
        this->dynamic_data.size = 0;\
    } else {\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
        TYPE* const stack_allocated_data__capacity_element = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, capacity);\
        TYPE const casted_capacity = (TYPE const)(capacity);\
        TYPE_METHOD(TYPE, construct_copy_at)(stack_allocated_data__capacity_element, &casted_capacity);\
    }\
    TYPE_METHOD(TYPE, construct_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this)));\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, shrink_to_fit)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this) {\
    if (this->is_stack_allocated) {\
        return this;\
    }\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const stack_allocated_string_capacity = (sizeof(this->dynamic_data) / sizeof(TYPE)) - 1;\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const string_size = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this);\
    if (string_size <= stack_allocated_string_capacity) {\
        TYPE temporary_buffer[(sizeof(this->dynamic_data) / sizeof(TYPE))];\
        for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < string_size; ++index) {\
            TYPE_METHOD(TYPE, construct_copy_at)(&temporary_buffer[index], SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(this, index));\
        }\
        TYPE_METHOD(ALLOCATOR, deallocate)(&this->allocator, this->dynamic_data.buffer, this->dynamic_data.capacity);\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, construct_from_buffer_at)(this, string_size, temporary_buffer);\
        return this;\
    }\
    TYPE* const temporary_buffer = TYPE_METHOD(ALLOCATOR, allocate)(&this->allocator, string_size + 1);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < string_size; ++index) {\
        TYPE_METHOD(TYPE, construct_copy_at)(&temporary_buffer[index], SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(this, index));\
    }\
    TYPE const null_terminate_character = '\0';\
    TYPE_METHOD(TYPE, construct_copy_at)(&temporary_buffer[string_size], &null_terminate_character);\
    TYPE_METHOD(ALLOCATOR, deallocate)(&this->allocator, this->dynamic_data.buffer, this->dynamic_data.capacity);\
    this->dynamic_data.buffer = temporary_buffer;\
    this->dynamic_data.capacity = string_size + 1;\
    return this;\
}\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const value) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, resize)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this) + 1, value);\
}\
MODIFIER void SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, pop_back)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this) {\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const size = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this);\
    TYPE_METHOD(TYPE, construct_at)(SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, size - 1));\
    if (this->is_stack_allocated) {\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
        TYPE const current_extension_size = (TYPE const)(capacity - size + 1);\
        TYPE* const stack_allocated_data__capacity_element = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(this, capacity);\
        TYPE_METHOD(TYPE, construct_copy_at)(stack_allocated_data__capacity_element, (TYPE const* const)(&current_extension_size));\
        return;\
    }\
    this->dynamic_data.size = size - 1;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_string)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* another_string) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_buffer)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, data)(another_string), SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(another_string));\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_c_string)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const * const source_buffer) {\
    STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size = RAW_STRING_FUNCTION(TYPE, length)(source_buffer);\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_buffer)(this, source_buffer, buffer_size);\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_buffer)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, TYPE const* const source_buffer, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const buffer_size) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this) + buffer_size);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < buffer_size; ++index) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(this, &source_buffer[index]);\
    }\
    return this;\
}\
MODIFIER struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, append_fill)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const size, TYPE const* const value) {\
    SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, reserve)(this, SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this) + size);\
    for (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index = 0u; index < size; ++index) {\
        SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, push_back)(this, value);\
    }\
    return this;\
}\
/* --- Getters functions implementation --- */\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this) {\
    if (this->is_stack_allocated) {\
        return (sizeof(this->dynamic_data) / sizeof(TYPE)) - 1;\
    }\
    return this->dynamic_data.capacity;\
}\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this) {\
    if (this->is_stack_allocated) {\
        STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) const capacity = SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, capacity)(this);\
        return (capacity - (STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type))(*SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(this, capacity)));\
    }\
    return this->dynamic_data.size;\
}\
MODIFIER STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, length)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this) {\
    return SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this);\
}\
MODIFIER uchar SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, empty)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this) {\
    return (uchar)!!SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, size)(this);\
}\
MODIFIER TYPE const* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, data)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this) {\
    return SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(this, 0u);\
}\
MODIFIER TYPE const* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR) const* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index) {\
    return (this->is_stack_allocated ? this->stack_data.buffer : this->dynamic_data.buffer) + index;\
}\
MODIFIER TYPE* SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHOD(TYPE, ALLOCATOR, mut_at)(struct SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR)* const this, STRUCT_SUBTYPE(SPECIALIZED_STRING_TYPE_WITH_CUSTOM_ALLOCATOR(TYPE, ALLOCATOR), size_type) index) {\
    return (this->is_stack_allocated ? this->stack_data.buffer : this->dynamic_data.buffer) + index;\
}

#define DEFINE_SPECIALIZED_STRING_METHODS_WITH_MODIFIER(MODIFIER, TYPE)\
    DEFINE_SPECIALIZED_STRING_WITH_CUSTOM_ALLOCATOR_METHODS_WITH_MODIFIER(MODIFIER, TYPE, DEFAULT_ALLOCATOR_TYPE(TYPE))

#define DEFINE_SPECIALIZED_STRING(TYPE) DEFINE_SPECIALIZED_STRING_METHODS_WITH_MODIFIER(, TYPE)

#define DEFINE_STRING() DEFINE_SPECIALIZED_STRING(char)
#define DEFINE_WSTRING() DEFINE_SPECIALIZED_STRING(wchar)

// predefine strings types/functions
#include <construct/characters_helpers.h>

DECLARE_STRING();
DECLARE_WSTRING();
DECLARE_SPECIALIZED_STRING(char8);
DECLARE_SPECIALIZED_STRING(char16);
DECLARE_SPECIALIZED_STRING(char32);
DECLARE_SPECIALIZED_STRING(char64);

#if defined(_WIN32)
    DECLARE_SPECIALIZED_STRING(winchar);
#endif
