#include "string.h"

DEFINE_STRING()
DEFINE_WSTRING()
DEFINE_SPECIALIZED_STRING(char8)
DEFINE_SPECIALIZED_STRING(char16)
DEFINE_SPECIALIZED_STRING(char32)
DEFINE_SPECIALIZED_STRING(char64)

#if defined(_WIN32)
    DEFINE_SPECIALIZED_STRING(winchar)
#endif
