#include "string.h"

IMPLEMENT_STRING()
IMPLEMENT_WSTRING()
IMPLEMENT_SPECIALIZED_STRING(char8)
IMPLEMENT_SPECIALIZED_STRING(char16)
IMPLEMENT_SPECIALIZED_STRING(char32)
IMPLEMENT_SPECIALIZED_STRING(char64)

#if defined(_WIN32)
    IMPLEMENT_SPECIALIZED_STRING(winchar)
#endif
