#include "allocator.h"

// common primitive types
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, char)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, short)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, int)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, long)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, llong)


DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uchar)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, ushort)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uint)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, ulong)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, ullong)


// fixed-width integers
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, int8)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, int16)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, int32)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, int64)


DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uint8)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uint16)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uint32)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uint64)


// character types
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, char8)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, char16)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, char32)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, char64)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, wchar)


// windows character type
#if defined(_WIN32)
    DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, winchar)
#endif


// pointer/data related types
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, usize)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, ptrdiff)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, intptr)
DEFINE_DEFAULT_ALLOCATOR_METHODS_WITH_MODIFIER(, uintptr)
