#include "atomic.h"

#include <construct/data_model_helpers.h>

// fixed-width integers
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, int8)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, int16)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, int32)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, int64)

DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, uint8)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, uint16)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, uint32)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, uint64)

// character types
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, char8)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, char16)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, char32)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, char64)

// pointer/data related types
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, usize)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, ptrdiff)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, intptr)
DEFINE_ATOMIC_METHODS_WITH_MODIFIER(, uintptr)
