#include "optional.h"


#include <construct/numeric_helpers.h>
// fixed-width integers
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, int8)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, int16)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, int32)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, int64)

DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, uint8)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, uint16)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, uint32)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, uint64)

#include <construct/characters_helpers.h>
// character types
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, char8)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, char16)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, char32)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, char64)

#include <construct/data_model_helpers.h>
// pointer/data related types
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, usize)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, ptrdiff)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, intptr)
DEFINE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(, uintptr)
