#pragma once

#include <containers/optional/optional.h>

// fixed-width integers
#include "fixed_size_types_aliases.h"
DEFINE_OPTIONAL_TYPE(int8);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, int8);
DEFINE_OPTIONAL_TYPE(int16);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, int16);
DEFINE_OPTIONAL_TYPE(int32);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, int32);
DEFINE_OPTIONAL_TYPE(int64);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, int64);

DEFINE_OPTIONAL_TYPE(uint8);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, uint8);
DEFINE_OPTIONAL_TYPE(uint16);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, uint16);
DEFINE_OPTIONAL_TYPE(uint32);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, uint32);
DEFINE_OPTIONAL_TYPE(uint64);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, uint64);

// character types
#include "characters_types_aliases.h"
DEFINE_OPTIONAL_TYPE(char8);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, char8);
DEFINE_OPTIONAL_TYPE(char16);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, char16);
DEFINE_OPTIONAL_TYPE(char32);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, char32);
DEFINE_OPTIONAL_TYPE(char64);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, char64);

// pointer/data related types
#include "data_model_types_aliases.h"
DEFINE_OPTIONAL_TYPE(usize);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, usize);
DEFINE_OPTIONAL_TYPE(ptrdiff);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, ptrdiff);
DEFINE_OPTIONAL_TYPE(intptr);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, intptr);
DEFINE_OPTIONAL_TYPE(uintptr);
DECLARE_OPTIONAL_METHODS_WITH_COMMON_MODIFIER(extern, uintptr);
